export {default as AdminLayout} from './AdminLayout'
// export {default as Dashboard} from './Dashboard'
export {default as ManageOrder} from './ManageOrder'
export {default as ManageProducts} from './ManageProducts'
export {default as Manageuser} from './Manageuser'
export {default as CreateProducts} from './CreateProducts'
export {default as Updateproducts} from './Updateproducts'
export {default as Manageblogs} from './Manageblogs'
export {default as Overview} from './Overview'
export {default as Managesupervise} from './Managesupervise'
export {default as Createdsupervise} from './Createdsupervise'
export {default as Updateblogs} from './Updateblogs'
export {default as Createdservices} from './Createdservices'
export {default as Manageservices} from './Manageservices'
export {default as Updateservice} from './Updateservice'
export {default as Managehotdistric} from './Managehotdistric'
export {default as Categoryservice} from './Categoryservice'
export {default as Managecounsel} from './Managecounsel'